@VoteMana = https://localhost:7045
@Code = PASTE_POLL_CODE
@VoterToken = PASTE_ANONYMOUS_VOTER_TOKEN_HERE

POST {{VoteMana}}/api/polls/{{Code}}/vote
Content-Type: application/json

{ "optionIndex": 0, "voterToken": "{{VoterToken}}" }

###
GET {{VoteMana}}/api/polls/{{Code}}/results