// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PollMana.Data;

#nullable disable

namespace PollMana.Migrations
{
    [DbContext(typeof(PollContext))]
    partial class PollContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PollMana.Models.Poll", b =>
                {
                    b.Property<long>("PollID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PollID"));

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CreatorUserID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsClosed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.HasKey("PollID");

                    b.HasIndex("CreatorUserID");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("Polls", (string)null);
                });

            modelBuilder.Entity("PollMana.Models.PollOption", b =>
                {
                    b.Property<long>("OptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("OptionID"));

                    b.Property<short>("OptionIndex")
                        .HasColumnType("smallint");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("PollID")
                        .HasColumnType("bigint");

                    b.HasKey("OptionID");

                    b.HasAlternateKey("PollID", "OptionID");

                    b.HasIndex("PollID", "OptionIndex")
                        .IsUnique();

                    b.ToTable("PollOptions", null, t =>
                        {
                            t.HasCheckConstraint("CHK_PollOptions_OptionIndex", "\"OptionIndex\" BETWEEN 0 AND 5");
                        });
                });

            modelBuilder.Entity("PollMana.Models.UserReference", b =>
                {
                    b.Property<string>("UserID")
                        .HasColumnType("text")
                        .HasColumnName("UserID");

                    b.HasKey("UserID");

                    b.ToTable("AspNetUsers", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("PollMana.Models.Poll", b =>
                {
                    b.HasOne("PollMana.Models.UserReference", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("PollMana.Models.PollOption", b =>
                {
                    b.HasOne("PollMana.Models.Poll", "Poll")
                        .WithMany("Options")
                        .HasForeignKey("PollID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("PollMana.Models.Poll", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
