// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VoteMana.Data;

#nullable disable

namespace VoteMana.Migrations
{
    [DbContext(typeof(VoteContext))]
    partial class VoteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VoteMana.Models.PollOptionReference", b =>
                {
                    b.Property<long>("PollOptionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("OptionID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PollOptionID"));

                    b.Property<long>("PollID")
                        .HasColumnType("bigint");

                    b.HasKey("PollOptionID");

                    b.ToTable("PollOptions", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("VoteMana.Models.PollReference", b =>
                {
                    b.Property<long>("PollID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PollID"));

                    b.HasKey("PollID");

                    b.ToTable("Polls", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("VoteMana.Models.Vote", b =>
                {
                    b.Property<long>("VoteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("VoteID"));

                    b.Property<long>("PollID")
                        .HasColumnType("bigint");

                    b.Property<long>("PollOptionID")
                        .HasColumnType("bigint");

                    b.Property<string>("VoterToken")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("VotedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("VoteID");

                    b.HasIndex("PollID", "PollOptionID");

                    b.HasIndex("PollID", "VoterToken")
                        .IsUnique();

                    b.ToTable("Vote", (string)null);
                });

            modelBuilder.Entity("VoteMana.Models.Vote", b =>
                {
                    b.HasOne("VoteMana.Models.PollReference", "Poll")
                        .WithMany()
                        .HasForeignKey("PollID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VoteMana.Models.PollOptionReference", "PollOption")
                        .WithMany()
                        .HasForeignKey("PollID", "PollOptionID")
                        .HasPrincipalKey("PollID", "PollOptionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poll");

                    b.Navigation("PollOption");

                });
#pragma warning restore 612, 618
        }
    }
}
