name: Backend CI Pipeline

on:
  pull_request:
    branches:
      - develop
    types: [opened, synchronize, reopened]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore PollBuilderCoursework.slnx

      - name: Build
        run: dotnet build PollBuilderCoursework.slnx --no-restore --configuration Release

      - name: Test
        run: dotnet test PollBuilderCoursework.slnx --no-build --configuration Release