name: Frontend CI Pipeline

on:
  pull_request:
    branches:
      - develop
    types: [opened, synchronize, reopened]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Run unit tests
        working-directory: frontend
        run: npm run test:unit --if-present

      - name: Build Vue app
        working-directory: frontend
        run: npm run build